// scripts/titles-extra2.mjs — third pass: warlords, releasables, achievements.
import fs from 'node:fs';
const dir = 'C:/Users/Atom/Documents/GeneralWS/hoi4-zh-wiki/data/batches/';
const M = {
  'Generic events MtG': '通用事件（MtG）', 'Generic events AAT': '通用事件（AAT）',
  'German events WtT': '德国事件（WtT）', 'German events MtG': '德国事件（MtG）',
  'German events GD': '德国事件（GD）', 'French events LaR': '法国事件（LaR）',
  'Finnish events AAT': '芬兰事件（AAT）', 'Czechoslovakian events PfOT': '捷克斯洛伐克事件（PfOT）',
  'Hungarian events DoD 1': '匈牙利事件（DoD 1）', 'Hungarian events DoD 2': '匈牙利事件（DoD 2）',
  'Icelandic events AAT': '冰岛事件（AAT）', 'Italian events BBA': '意大利事件（BBA）',
  'Japanese events WtT': '日本事件（WtT）', 'Polish events NSB': '波兰事件（NSB）',
  'Romanian events DoD': '罗马尼亚事件（DoD）', 'Spanish events LaR': '西班牙事件（LaR）',
  'Soviet events NSB': '苏联事件（NSB）', 'Soviet events NSB 2': '苏联事件（NSB 2）',
  'Soviet events WtT': '苏联事件（WtT）', 'Yugoslavian events DoD': '南斯拉夫事件（DoD）',
  'News events 1': '新闻事件 1', 'News events 2': '新闻事件 2', 'News events 3': '新闻事件 3',
  'News events 4': '新闻事件 4', 'News events AAT': '新闻事件（AAT）', 'News events BftB': '新闻事件（BftB）',
  'News events DoD': '新闻事件（DoD）', 'News events LaR': '新闻事件（LaR）',
  'News events MtG': '新闻事件（MtG）', 'News events WtT': '新闻事件（WtT）',
  // releasables & regions
  'Releasable countries/Africa': '可释放国家/非洲', 'Releasable countries/Asia': '可释放国家/亚洲',
  'Releasable countries/Europe': '可释放国家/欧洲', 'Releasable countries/Americas': '可释放国家/美洲',
  'Releasable countries/Oceania': '可释放国家/大洋洲',
  'Releasable countries/Soviet Union': '可释放国家/苏联',
  'Formable nations/Africa': '可成立国家/非洲', 'Formable nations/Asia': '可成立国家/亚洲',
  'Formable nations/Europe': '可成立国家/欧洲', 'Formable nations/North America': '可成立国家/北美洲',
  'Formable nations/South America': '可成立国家/南美洲', 'Formable nations/Oceania': '可成立国家/大洋洲',
  'Horn of Africa nations': '非洲之角国家', 'Indian Princely States': '印度土邦',
  'Indonesian Princely States': '印度尼西亚土邦',
  // chinese warlords & factions
  'Gansu Ma': '甘马（马家军）', 'Qinghai Ma': '青马（马家军）', 'Ningxia Ma': '宁马（马家军）',
  'Guangxi Clique': '桂系', 'Guangdong Clique': '粤系', 'Shandong Clique': '鲁系',
  'Sichuan Clique': '川系', 'Shanxi': '晋系', 'Yunnan': '滇系', 'Sinkiang': '新疆',
  'Xinjiang': '新疆', 'Tibet': '西藏', 'Khotan Ma': '和田马家军', 'Kumul Khanate': '哈密汗国',
  'Northeastern Army': '东北军', 'Hebei-Chahar': '冀察', 'Mengjiang': '蒙疆',
  'Reorganized National Government of the Republic of China': '中华民国南京国民政府',
  'Second Philippine Republic': '菲律宾第二共和国', 'Nepal': '尼泊尔', 'Saudi Arabia': '沙特阿拉伯',
  'Yemen': '也门', 'Slovakia': '斯洛伐克', 'Sudetenland': '苏台德', 'Tannu Tuva': '唐努乌梁海',
  'Vojvodina': '伏伊伏丁那', 'Vichy France': '维希法国', 'Free France': '自由法国',
  'Free City of Danzig': '但泽自由市', 'Protektorat Böhmen-Mähren': '波希米亚和摩拉维亚保护国',
  'Independent State of Croatia': '克罗地亚独立国', 'Galicia and Lodomeria': '加利西亚和洛多梅里亚',
  'Republic of Syria': '叙利亚共和国', 'Lebanese Republic': '黎巴嫩共和国',
  'Sheikhdom of Kuwait': '科威特酋长国', 'Emirate of Pashtunistan': '普什图尼斯坦酋长国',
  'Mandatory Palestine': '英属巴勒斯坦托管地', 'Sultanate of Aussa': '奥萨苏丹国',
  'Italian State of East Africa': '意属东非', 'Kuban National Republic': '库班民族共和国',
  'Don Cossack Host': '顿河哥萨克', 'United Baltic Duchy': '波罗的海联合公国',
  'Reichskommissariats': '帝国专员辖区', 'Governments in exile': '流亡政府',
  'Imperial influence': '帝国影响力', 'Internal factions': '内部派系',
  'Unaligned States of America': '不结盟的美利坚合众国', 'New World Order': '世界新秩序',
  'Jan Mayen': '扬马延', 'Old Zealand': '旧西兰',
  // systems
  'Land battle': '陆战', 'War participation': '战争贡献', 'Recruitable population': '可招募人口',
  'Strategic region': '战略区域', 'Military industrial organization': '军工组织',
  'Special forces doctrine': '特种部队学说', 'Missile': '导弹', 'Nuclear bomb': '核弹',
  'Operations': '行动', 'Operatives': '特工', 'Raid': '突袭', 'Scientist': '科学家',
  'Launch options': '启动参数', 'Ironman': '铁人模式', 'International market': '国际市场',
  'London Naval Treaty': '伦敦海军条约', 'Spanish Civil War layout': '西班牙内战版图',
  'The Second Sino-Japanese War': '第二次中日战争', 'Historical divisions': '历史师编制',
  'Land doctrine/Sample divisions with doctrine bonuses': '陆军学说/带学说加成的示例师',
  'Main Page/news': '首页/新闻', 'Main Page/links': '首页/链接',
  'Hearts of Iron 4 Wiki': '钢铁雄心 IV 维基', 'Downloadable content 2': '可下载内容 2',
  'Vic2ToHoI4: Focus Trees': 'Vic2 转 HoI4：国策树',
  'Victoria 3 to Hearts of Iron IV converter': '维多利亚 3 转钢铁雄心 4 转换器',
  'HOI4 ULTRA (Historical Industry Project)': 'HOI4 ULTRA（历史工业计划）',
  // achievements / mods (keep the pun, add a gloss where useful)
  'Crusader Kings IV': '十字军之王 IV（Crusader Kings IV）', 'Danzig queen': '但泽女王（Danzig queen）',
  'Czechmate': '将死（Czechmate）', 'Crush the Dream': '粉碎梦想（Crush the Dream）',
  "Don't Die for Your Country": '别为你的国家送死（Don\'t Die for Your Country）',
  'Don’t Die for Your Country': '别为你的国家送死（Don’t Die for Your Country）',
  'Equestria At War': '小马国战争（Equestria At War）', 'Esti is Scandi': '爱沙尼亚属斯堪的纳维亚（Esti is Scandi）',
  'From Tehran with Love': '来自德黑兰的爱（From Tehran with Love）',
  'Go Ahead, Macau My Day': '来吧，澳门我的天（Go Ahead, Macau My Day）',
  'Hail to the King': '国王万岁（Hail to the King）', 'Hail to the Qing': '大清万岁（Hail to the Qing）',
  'Hardly Anything Sèvres': '几乎没剩下什么（Hardly Anything Sèvres）',
  'Holy, Roman, and an Empire': '神圣、罗马且是一个帝国（Holy, Roman, and an Empire）',
  'House of Kurds': '库尔德人之家（House of Kurds）', 'Huge-oslavia': '大南斯拉夫（Huge-oslavia）',
  "I didn't hear no bell": '我没听到铃声（I didn\'t hear no bell）',
  'It has my name on it': '上面写着我的名字（It has my name on it）',
  'Its all coming together': '一切正在成形（Its all coming together）',
  'Istanbul is Constantinople. Again.': '伊斯坦布尔又是君士坦丁堡了（Istanbul is Constantinople. Again.）',
  'Kaiserreich': '德意志帝国（Kaiserreich）', 'Lamento Boliviano': '玻利维亚悲歌（Lamento Boliviano）',
  'Lone Wolf': '独狼（Lone Wolf）', 'Media Mughal': '媒体莫卧儿（Media Mughal）',
  'Maphilindia': '马来菲利印度（Maphilindia）',
  'Miklos Horthy and the Habsburg Prince': '霍尔蒂与哈布斯堡王子（Miklos Horthy and the Habsburg Prince）',
  'Mughal West Britain Company': '莫卧儿西不列颠公司（Mughal West Britain Company）',
  'My Ships Don\'t Lie': '我的船不会说谎（My Ships Don\'t Lie）',
  'Neither Death nor Dishonor': '既非死亡亦非耻辱（Neither Death nor Dishonor）',
  'No more Partitions': '不再有瓜分（No more Partitions）',
  'No one crosses the finnish line': '没人能越过芬兰线（No one crosses the finnish line）',
  'Norway Jose': '挪威，何塞（Norway Jose）', 'Oh, how the turntables': '风水轮流转（Oh, how the turntables）',
  'Oil Sheiks': '石油酋长（Oil Sheiks）', 'One King, Two Crowns': '一王两冠（One King, Two Crowns）',
  'Our Other Place in the Sun': '我们阳光下的另一块地方（Our Other Place in the Sun）',
  'Otto-man': '奥托曼（Otto-man）', 'Paradisus Paradoxum': '悖论乐园（Paradisus Paradoxum）',
  "Party like it's 1520": '像 1520 年那样狂欢（Party like it\'s 1520）',
  'Pinot Noirway': '黑皮诺挪威（Pinot Noirway）', 'Rule Britannia': '统治不列颠（Rule Britannia）',
  'Sapmi united by the fire': '火边的萨米团结（Sapmi united by the fire）',
  'Siberian Tiger': '西伯利亚虎（Siberian Tiger）', 'Sunrise Invasion': '日出入侵（Sunrise Invasion）',
  'The 501st Legion': '第 501 军团（The 501st Legion）', 'The Danelaw': '丹麦法区（The Danelaw）',
  'The Dragon Rises': '巨龙崛起（The Dragon Rises）',
  'The Dragon Swallowed the Sun': '巨龙吞日（The Dragon Swallowed the Sun）',
  'The Legacy of Cyrus the Great': '居鲁士大帝的遗产（The Legacy of Cyrus the Great）',
  'The Lenin Boys are Back in Town': '列宁小子们回来了（The Lenin Boys are Back in Town）',
  'The Lion King': '狮子王（The Lion King）', 'The Magic School Bus': '神奇校车（The Magic School Bus）',
  'The Neverending Story': '永无止境的故事（The Neverending Story）',
  'The People Have Stood Up!': '人民站起来了！（The People Have Stood Up!）',
  'The Red Sea': '红海（The Red Sea）', 'The Road to 56': '通往 56 之路（The Road to 56）',
  'The Romanovs laugh last': '罗曼诺夫笑到最后（The Romanovs laugh last）',
  'The Soviet Onion': '苏联洋葱（The Soviet Onion）',
  'The Sun Will Never Set': '日不落（The Sun Will Never Set）',
  'The True Successor': '真正的继承者（The True Successor）',
  'The return of the king': '王者归来（The return of the king）',
  "That's Sikh!": '那才叫锡克！（That\'s Sikh!）',
  'This Achievement is Cheesy': '这成就太俗套了（This Achievement is Cheesy）',
  'This achievement is dedicated to the brave soldiers of...': '本成就献给勇敢的士兵们……',
  'This is going to be LIT': '这要火了（This is going to be LIT）',
  'This time for Africa': '这次为了非洲（This time for Africa）',
  'Tour de France': '环法自行车赛（Tour de France）',
  'Treading the Narrow Path': '走在窄路上（Treading the Narrow Path）',
  'True Blitzkrieg': '真正的闪电战（True Blitzkrieg）',
  'Uralic brothers united': '乌拉尔兄弟团结（Uralic brothers united）',
  'United Netherlands (achievement)': '尼德兰联合王国（成就）',
  "We're Putting the Band Back Together": '我们重组乐队（We\'re Putting the Band Back Together）',
  'We’re Putting the Band Back Together': '我们重组乐队（We’re Putting the Band Back Together）',
  'William Wallis': '威廉·华莱士（William Wallis）',
  'Woman in a High Castle': '高堡中的女人（Woman in a High Castle）',
  'You Shall Not Pass': '你不能通过（You Shall Not Pass）',
  '…and you get a canton, everybody gets a canton!': '……你得到一个州，每个人都得到一个州！',
  'Peace for Our Time': '我们时代的和平', 'Thunder at Our Gates': '雷霆临门',
  'Paradox': 'Paradox',
};

const src = JSON.parse(fs.readFileSync(dir + 'titles.json', 'utf8'));
const prev = JSON.parse(fs.readFileSync(dir + 'titles.zh.json', 'utf8'));
const zhByKey = new Map(prev.items.map((i) => [i.k, i.zh]));
let fixed = 0;
for (const u of src.units) {
  if (M[u.en] && zhByKey.get(u.k) === u.en) { zhByKey.set(u.k, M[u.en]); fixed++; }
}
const stillEnglish = src.units.filter((u) => zhByKey.get(u.k) === u.en).map((u) => u.en);
fs.writeFileSync(dir + 'titles.zh.json', JSON.stringify({ batch: 'titles', items: src.units.map((u) => ({ k: u.k, zh: zhByKey.get(u.k) })) }, null, 1));
console.log('applied:', fixed, '| remaining english titles:', stillEnglish.length);
console.log(stillEnglish.join(' | '));
