// scripts/titles-extra.mjs — second pass mapping for the remaining page titles.
import fs from 'node:fs';
const dir = 'C:/Users/Atom/Documents/GeneralWS/hoi4-zh-wiki/data/batches/';
const missing = fs.readFileSync(dir + 'titles-missing.txt', 'utf8').split('\n').filter(Boolean);

const M = {
  // --- countries / regions ---
  'Bhutan': '不丹', 'Bolivia': '玻利维亚', 'British Malaya': '英属马来亚', 'British Burma': '英属缅甸',
  'Dominion of Canada': '加拿大自治领', 'East Germany': '东德', 'West Germany': '西德',
  'Emirate of Transjordan': '外约旦酋长国', 'Confederacy of American States': '美利坚联盟国',
  'Carpatho-Ukraine': '喀尔巴阡乌克兰', 'Dalmatia': '达尔马提亚', 'Al-Andalus': '安达卢斯',
  'Australia-Hungary': '澳匈帝国', 'Ancient Formable Nations': '古代可成立国家',
  'Baltic events NSB': '波罗的海国家事件（NSB）', 'British events MtG': '英国事件（MtG）',
  'British events WtT': '英国事件（WtT）', 'American events MtG': '美国事件（MtG）',
  'Bulgarian events BftB': '保加利亚事件（BftB）', 'Chinese events WtT': '中国事件（WtT）',
  'Caribbean states': '加勒比国家', 'Central American states': '中美洲国家',
  'South American states': '南美洲国家', 'African states': '非洲国家', 'Asian states': '亚洲国家',
  'European states': '欧洲国家', 'Middle Eastern states': '中东国家',
  // --- game systems ---
  'Aircraft': '飞机', 'Commander': '指挥官', 'Civil war': '内战', 'Continuous focus': '持续焦点',
  'Country creation': '国家创建', 'Division designer': '师编制设计', 'Difficulty': '难度',
  'Balance of power': '力量均势', 'Border war': '边境战争', 'Convoy': '运输船队',
  'Convoys': '运输船队', 'Equipment designer': '装备设计商', 'Expeditionary force': '远征军',
  'Historical units': '历史部队', 'Military staff': '军事参谋', 'Materiel designer': '装备设计商',
  'Political advisor': '政治顾问', 'Industrial concern': '工业集团', 'High command': '最高统帅部',
  'Theatre': '战区', 'Weather': '天气', 'Terrain': '地形', 'State': '州', 'States': '州',
  'Province': '省份', 'Provinces': '省份', 'Victory points': '胜利点', 'Naval invasion': '海军登陆',
  'Naval supremacy': '制海权', 'Air superiority': '制空权', 'Air wing': '航空队',
  'Strategic bombing': '战略轰炸', 'Close air support': '近距空中支援', 'Naval strike': '海上打击',
  'Mine warfare': '水雷战', 'Minelaying': '布雷', 'Minesweeping': '扫雷', 'Reconnaissance': '侦察',
  'Supply': '补给', 'Supply areas': '补给区', 'Fuel': '燃料', 'Manpower': '人力',
  'Resistance': '抵抗运动', 'Compliance': '顺从度', 'Garrison': '驻军', 'Autonomy': '自治度',
  'Puppets': '傀儡国', 'Subject': '附庸国', 'Subjects': '附庸国', 'Faction leader': '阵营领袖',
  'Guarantee': '保障独立', 'Non-aggression pact': '互不侵犯条约', 'War goal': '战争目标',
  'Peace conference': '和平会议', 'Capitulation': '投降', 'Surrender': '投降',
  'Volunteer': '志愿军', 'Volunteers and expeditionary forces': '志愿军与远征军',
  'Special forces': '特种部队', 'Paratroopers': '伞兵', 'Marines': '海军陆战队',
  'Mountaineers': '山地兵', 'Armor': '装甲', 'Tanks': '坦克', 'Ships': '舰船',
  'Ship': '舰船', 'Submarine': '潜艇', 'Destroyer': '驱逐舰', 'Cruiser': '巡洋舰',
  'Battleship': '战列舰', 'Carrier': '航空母舰', 'Convoy escort': '护航', 'Radar': '雷达',
  'Rocket': '火箭', 'Nuclear': '核武器', 'Atomic research': '原子能科研',
  'Intelligence': '情报', 'Operative': '特工', 'Cipher': '密码', 'Decryption': '解密',
  'Achievement': '成就', 'Achievements modding': '成就模组制作', 'Career profile': '生涯档案',
  'Console commands': '控制台指令', 'Modding': '模组制作', 'Mod structure': '模组结构',
  'Graphical asset modding': '图形资源模组制作', 'Interface modding': '界面模组制作',
  'Localisation modding': '本地化模组制作', 'Nudger': '地图编辑器',
  'Troubleshooting': '疑难排查', 'Bookmark': '书签', 'Bookmark modding': '书签模组制作',
  'Doctrine modding': '学说模组制作', 'Unit modding': '单位模组制作',
  'Equipment modding': '装备模组制作', 'Idea modding': '理念模组制作',
  'Character modding': '人物模组制作', 'Building modding': '建筑模组制作',
  'Scopes': '作用域', 'On actions': '事件钩子', 'AI focuses': 'AI 焦点',
  'AI modding': 'AI 模组制作', 'Civil war modding': '内战模组制作',
  'Cosmetic tag modding': '外观标签模组制作', 'Font modding': '字体模组制作',
  'Ideology modding': '意识形态模组制作', 'Military industrial organization modding': '军工组织模组制作',
  'Scripted GUI modding': '脚本界面模组制作', 'Faction modding': '阵营模组制作',
  'Event modding': '事件模组制作', 'Decision modding': '决议模组制作',
  'Technology modding': '科技模组制作', 'Map modding': '地图模组制作',
  'State modding': '州模组制作', 'Supply areas modding': '补给区模组制作',
  'Portrait modding': '头像模组制作', 'National focus modding': '国家焦点模组制作',
  'Data structures': '数据结构', 'Modifiers': '修正项', 'Modifier': '修正项',
  'Trigger': '触发器', 'Triggers': '触发器', 'Effect': '效果', 'Effects': '效果',
  'Defines': '定义文件', 'Scripted effects': '脚本效果', 'Dynamic modifiers': '动态修正项',
  'Opinion': '好感度', 'Relations': '外交关系', 'Improve relations': '改善关系',
  'Justify war goal': '制造战争目标', 'War justification': '战争目标制造',
  'Lend lease': '租借', 'Lend-Lease': '租借', 'Attaché': '武官', 'Attaches': '武官',
  'Guarantees': '保障独立', 'Requests': '请求', 'Events': '事件', 'News events': '新闻事件',
  'Decision': '决议', 'Missions': '任务', 'Continuous focuses': '持续焦点',
  'Focus tree': '国策树', 'Focus': '焦点', 'National focuses': '国家焦点',
  'Political power': '政治点数', 'Command power': '指挥点数', 'Stability': '稳定度',
  'War support': '战争支持度', 'World tension': '世界紧张度', 'Ideology': '意识形态',
  'Election': '选举', 'Elections': '选举', 'Coup': '政变', 'Advisor': '顾问',
  'Advisors': '顾问', 'Law': '法令', 'Laws': '法令', 'National spirit': '国家精神',
  'National spirits': '国家精神', 'Idea': '理念', 'Ideas': '理念',
  'Research': '科研', 'Research slot': '科研槽', 'Technology': '科技',
  'Production': '生产', 'Factory': '工厂', 'Factories': '工厂', 'Construction': '建造',
  'Resource': '资源', 'Resources': '资源', 'Trade': '贸易', 'Logistics': '后勤',
  'Attrition': '损耗', 'Encirclement': '包围', 'Combat': '战斗', 'Combat width': '战斗宽度',
  'Organisation': '组织度', 'Organization': '组织度', 'Experience': '经验',
  'Army': '陆军', 'Navy': '海军', 'Air force': '空军', 'Division': '师', 'Divisions': '师',
  'Brigade': '旅', 'Regiment': '团', 'Battalion': '营', 'Company': '连',
  'Support company': '支援连', 'Support companies': '支援连', 'Template': '编制模板',
  'Tactic': '战术', 'Combat tactics': '战斗战术', 'Battle plan': '作战计划',
  'Planning bonus': '计划加成', 'Entrenchment': '构筑工事', 'Fort': '要塞',
  'Terrain types': '地形类型', 'River': '河流', 'Forest': '森林', 'Urban': '城市',
  'Mountain': '山地', 'Desert': '沙漠', 'Marsh': '沼泽', 'Plains': '平原', 'Jungle': '丛林',
  'Naval': '海军', 'Naval units': '海军单位', 'Air units': '空军单位',
  'Land units': '陆军单位', 'Units': '单位', 'Equipment': '装备',
  'Designer': '设计商', 'Variant': '型号', 'Module': '模块', 'Slot': '插槽',
  'Patch': '补丁', 'Developer diaries': '开发日志', 'DLC': 'DLC',
  'Downloadable content': '可下载内容', 'Mods': '模组', 'Jargon': '术语表',
  'Achievements': '成就', 'Guide': '指南', 'Tutorial': '教学',
  // --- achievements: keep the official English names, add a short zh gloss ---
  'A Great Hunger': '大饥荒（A Great Hunger）',
  'Ain\'t like that now': '今非昔比（Ain\'t like that now）',
  'Antischluss': '反德奥合并（Antischluss）',
  'Awake and Angry': '觉醒与愤怒（Awake and Angry）',
  'Backhand Blow': '反手一击（Backhand Blow）',
  'Bad Ending - The whole world is now Brazil': '坏结局——全世界都成了巴西',
  'Bad Romeance': '罗马式浪漫（Bad Romeance）',
  'Balance of power': '力量均势',
  'Balkan Problem Solved': '巴尔干问题已解决（Balkan Problem Solved）',
  'Battle Royale': '大逃杀（Battle Royale）',
  'Battlecry': '战吼（Battlecry）',
  'Battlefleet Concentration': '主力舰队集中（Battlefleet Concentration）',
  'Bearer of Artillery': '火炮持有者（Bearer of Artillery）',
  'Big Entente': '大协约（Big Entente）',
  'Border war': '边境战争',
  'Brentry': '英国入欧（Brentry）',
  'Bullseye': '正中靶心（Bullseye）',
  'By Beer Alone': '仅凭啤酒（By Beer Alone）',
  'Caramelldansen': '焦糖舞（Caramelldansen）',
  'Cheese your fighter.': '给你的战斗机加奶酪（Cheese your fighter.）',
  'Chilean Empire': '智利帝国（Chilean Empire）',
  'Cod wars': '鳕鱼战争（Cod wars）',
  'Congolese Belgium': '刚果化的比利时（Congolese Belgium）',
  'Crusader Kings': '十字军之王（Crusader Kings）',
  'Crusader Kings 2': '十字军之王 2（Crusader Kings 2）',
  'Death or Dishonor or Cake': '死亡、耻辱或蛋糕（Death or Dishonor or Cake）',
  'Delay': '迟滞（Delay）',
  'Elastic Defense': '弹性防御（Elastic Defense）',
  'Infiltration Assault': '渗透突击（Infiltration Assault）',
  'Mechanized Offensive': '机械化攻势（Mechanized Offensive）',
  'Naval Strike Torpedo Tactics': '海军打击鱼雷战术（Naval Strike Torpedo Tactics）',
  'Submarine Operations': '潜艇作战（Submarine Operations）',
  '30 Minutes of Hel': '地狱三十分钟（30 Minutes of Hel）',
  'America Decolonized!': '美国去殖民化！（America Decolonized!）',
  'Contact us': '联系我们', 'Construction/landmarkrow': '建造/地标行模板',
  'Cobalt Sea': '钴蓝海（Cobalt Sea）',
  'Spirit': '精神（消歧义）', 'Trait': '特质（消歧义）', 'Reconnaissance': '侦察（消歧义）',
  'Organization': '组织度（消歧义）', 'Kingdom of Burundi': '布隆迪王国（消歧义）',
  'Guinea (disambiguation)': '几内亚（消歧义）', 'United Netherlands (disambiguation)': '尼德兰联合王国（消歧义）',
  'Spain': '西班牙（消歧义）', 'Congo': '刚果（消歧义）',
};

const all = fs.readFileSync(dir + 'titles.json', 'utf8');
const src = JSON.parse(all);
const prev = JSON.parse(fs.readFileSync(dir + 'titles.zh.json', 'utf8'));
const zhByKey = new Map(prev.items.map((i) => [i.k, i.zh]));
let fixed = 0, stillEnglish = [];
for (const u of src.units) {
  const cur = zhByKey.get(u.k);
  if (M[u.en] && (cur === u.en || !cur)) { zhByKey.set(u.k, M[u.en]); fixed++; }
}
for (const u of src.units) if (zhByKey.get(u.k) === u.en) stillEnglish.push(u.en);
fs.writeFileSync(dir + 'titles.zh.json', JSON.stringify({ batch: 'titles', items: src.units.map((u) => ({ k: u.k, zh: zhByKey.get(u.k) })) }, null, 1));
console.log('extra mappings applied:', fixed);
console.log('remaining english titles:', stillEnglish.length);
fs.writeFileSync(dir + 'titles-missing.txt', stillEnglish.join('\n'));
console.log(stillEnglish.join(' | '));
