// Supplementary shared glossary: high-frequency wiki strings translated once so they
// render in Chinese on every page. Exact matches first, then placeholder-aware patterns.
// Patterns carry literal ⟦n⟧ tokens in BOTH key and value; the value's tokens are
// reconciled against the source tokens at build time.
export const EXACT = {
  // ---- table headers & UI labels ----
  'Traits': '特质', 'Popularity': '支持率', 'Portrait': '肖像', 'Possible': '可用', 'Type': '类型',
  'Country name': '国家名称', 'Strategies and guides': '策略与指南', 'Historical background': '历史背景',
  'Party': '党派', 'Conscription Law': '征兵法案', 'Trade Law': '贸易法案', 'Economy': '经济',
  'Theorists': '理论家', 'Air force': '空军', 'Geography': '地理', 'Staff and designers': '参谋与设计商',
  'Initial trait': '初始特质', 'Manpower used': '已用人力', 'Companies': '公司', 'Cosmetic names': '外观名称',
  'Logo': '标志', 'Combat battalions': '战斗营', 'Designers': '设计商', 'Name list': '名称列表',
  'Organizations': '组织', 'Personnel': '人员', 'Political parties': '政党', 'Air Technology': '空军科技',
  'Army Technology': '陆军科技', 'Electronics & Industry': '电子与工业', 'Materiel organizations': '装备组织',
  'Motorization': '摩托化', 'Naval Technology': '海军科技', 'Political Advisors': '政治顾问',
  'Ship organizations': '舰船组织', 'Tank organizations': '坦克组织', 'Building Slots': '建筑槽位',
  'Civilian Factories': '民用工厂', 'Military Factories': '军用工厂', 'Naval Dockyards': '海军船坞',
  'Total divisions': '师总数', 'Cities': '城市', 'State table': '州列表', 'Weapons and Equipment': '武器与装备',
  'Achievement guides': '成就攻略', 'Skill': '技能', 'Mountain': '山地',
  'Affected equipment:': '受影响装备：', 'Always available': '始终可用', 'Bonuses:': '加成：',
  'Requirements:': '需求：', 'Research categories:': '研究类别：', 'Infantry Weapons': '步兵武器',
  'Motorized': '摩托化', 'Mechanized': '机械化', 'Armored': '装甲', 'Artillery': '火炮',
  'Anti-Air': '防空', 'Anti-Tank': '反坦克', 'Support Artillery': '支援火炮', 'Field Hospital': '野战医院',
  'Maintenance Company': '维修连', 'Logistics Company': '后勤连', 'Signal Company': '通信连',
  'Military Police': '军事警察', 'Engineer Company': '工兵连', 'Recon Company': '侦察连',
  'Super Heavy': '超重型', 'Heavy': '重型', 'Medium': '中型', 'Light': '轻型', 'Amphibious': '两栖',
  'Naval Invasion': '海上登陆', 'Airborne': '空降', 'Paradrop': '空降', 'Garrison': '驻军',
  'Strategic Redeployment': '战略调动', 'Exercise': '演习', 'Excercise': '演习',
  'Justify war goal': '制造战争目标', 'Declare war': '宣战', 'Call to arms': '号召参战',
  'Guarantee': '保障独立', 'Non-Aggression Pact': '互不侵犯条约', 'Military Access': '军事通行权',
  'Expeditionary Force': '远征军', 'Volunteers': '志愿军', 'Lend-Lease': '租借',
  'Request Lend-Lease': '请求租借', 'Send Lend-Lease': '提供租借', 'Faction': '阵营',
  'Create Faction': '创建阵营', 'Invite to Faction': '邀请加入阵营', 'Puppet': '傀儡国',
  'Annex': '吞并', 'Liberate': '解放', 'Satellite': '卫星国', 'War score': '战争贡献',
  'Peace conference': '和平会议', 'Capitulate': '投降', 'Surrender': '投降', 'Compliance': '顺从度',
  'Resistance': '抵抗度', 'Occupation law': '占领法案', 'Resistance target': '抵抗度目标',
  'Intelligence agency': '情报机构', 'Operative': '特工', 'Spy network': '间谍网络',
  'Cryptology': '密码学', 'Decryption': '解密', 'Encryption': '加密', 'Naval supremacy': '海上优势',
  'Air superiority': '空中优势', 'Naval invasion': '海上登陆', 'Convoy raiding': '破交作战',
  'Anti-submarine warfare': '反潜作战', 'Close air support': '近距空中支援',
  'Strategic bombing': '战略轰炸', 'Naval strike': '海上打击', 'Port strike': '港口打击',
  'Logistical strike': '后勤打击', 'Reconnaissance': '侦察', 'Railway gun': '铁道炮',
  'Railway': '铁路', 'Supply hub': '补给中心', 'Supply': '补给', 'Fuel': '燃料',
  'Fuel silo': '燃料储罐', 'Refinery': '炼油厂', 'Synthetic refinery': '合成炼油厂',
  'Infrastructure': '基础设施', 'Air base': '空军基地', 'Naval base': '海军基地',
  'Radar station': '雷达站', 'Coastal fort': '海岸炮台', 'Land fort': '陆地要塞',
  'Victory points': '胜利点', 'Building slot': '建筑槽位', 'Resource': '资源', 'Resources': '资源',
  'Equipment': '装备', 'Manpower': '人力', 'Research': '科研', 'Technology': '科技',
  'Doctrine': '学说', 'Focus': '国策', 'Decision': '决议', 'Event': '事件', 'Mission': '任务',
  'Continuous focus': '持续国策', 'National focus': '国家焦点', 'Focus tree': '国策树',
  'Political power': '政治点数', 'Command power': '指挥点数', 'Stability': '稳定度',
  'War support': '战争支持度', 'World tension': '世界紧张度', 'Ideology': '意识形态',
  'Democratic': '民主', 'Communist': '共产', 'Fascist': '法西斯', 'Neutrality': '中立',
  'Elections': '选举', 'Referendum': '公投', 'Coup': '政变', 'Civil war': '内战',
  'Front line': '前线', 'Orders': '命令', 'Fallback line': '撤退线', 'Offensive line': '进攻线',
  'Garrison area': '驻防区域', 'Army': '陆军', 'Navy': '海军', 'Air': '空军',
  'Division template': '师编制', 'Army experience': '陆军经验', 'Navy experience': '海军经验',
  'Air experience': '空军经验', 'Political power cost': '政治点数花费',
};

/** [source containing literal ⟦n⟧ tokens, translation containing the same tokens] */
export const PATTERNS = [
  ['⟦0⟧ Recruitable population', '⟦0⟧ 可征召人口'],
  ['⟦0⟧ Resources to market', '⟦0⟧ 出口到市场的资源'],
  ['⟦0⟧ Civilian intelligence to others', '⟦0⟧ 向他国民事情报'],
  ['⟦0⟧ Navy intelligence to others', '⟦0⟧ 向他国海军情报'],
  ['⟦0⟧ Construction speed', '⟦0⟧ 建造速度'],
  ['⟦0⟧ Factory construction speed', '⟦0⟧ 工厂建造速度'],
  ['⟦0⟧ Factory conversion cost', '⟦0⟧ 工厂转换花费'],
  ['⟦0⟧ Factory/Dockyard output', '⟦0⟧ 工厂／船坞产出'],
  ['⟦0⟧ Factory Energy Consumption', '⟦0⟧ 工厂能源消耗'],
  ['⟦0⟧ Fuel gain per oil', '⟦0⟧ 每单位石油的燃料产量'],
  ['⟦0⟧ Fuel capacity', '⟦0⟧ 燃料容量'],
  ['⟦0⟧ Research speed', '⟦0⟧ 科研速度'],
  ['⟦0⟧ Expected number of factories put on Consumer Goods', '⟦0⟧ 预计投入消费品生产的工厂数'],
  ['⟦0⟧ Market construction boost multiplier', '⟦0⟧ 市场建造加成倍率'],
  ['⟦0⟧ Gain: ⟦1⟧ daily', '⟦0⟧ 获取：每日 ⟦1⟧'],
  ['⟦0⟧ (# prov)', '⟦0⟧（省份数）'],
  ['Soft attack: ⟦0⟧', '软攻：⟦0⟧'],
  ['Hard attack: ⟦0⟧', '硬攻：⟦0⟧'],
  ['Air Attack: ⟦0⟧', '对空攻击：⟦0⟧'],
  ['Air Defence: ⟦0⟧', '对空防御：⟦0⟧'],
  ['Light Attack: ⟦0⟧', '轻型攻击：⟦0⟧'],
  ['Stability: ⟦0⟧', '稳定度：⟦0⟧'],
  ['Surface detection: ⟦0⟧', '水面探测：⟦0⟧'],
  ['Division Defense: ⟦0⟧', '师防御：⟦0⟧'],
  ['Division Attack: ⟦0⟧', '师攻击：⟦0⟧'],
  ['Fuel Usage: ⟦0⟧', '燃料消耗：⟦0⟧'],
  ['Factory Energy Consumption: ⟦0⟧', '工厂能源消耗：⟦0⟧'],
  ['Air Superiority: ⟦0⟧', '空中优势：⟦0⟧'],
  ['Hardness: ⟦0⟧', '硬度：⟦0⟧'],
  ['Production output: ⟦0⟧', '产出：⟦0⟧'],
  ['Production output cost: ⟦0⟧', '产出花费：⟦0⟧'],
  ['Production resource need: ⟦0⟧', '生产资源需求：⟦0⟧'],
  ['Production cost: ⟦0⟧', '生产成本：⟦0⟧'],
  ['Military Industrial Organization Research Bonus: ⟦0⟧', '军工组织科研加成：⟦0⟧'],
  ['Design Team Assign Cost: ⟦0⟧', '设计团队指派花费：⟦0⟧'],
  ['Design companies of ⟦0⟧.', '⟦0⟧ 的设计公司。'],
  ['Equipment: Reliability: ⟦0⟧', '装备：可靠性：⟦0⟧'],
  ['Equipment: Defense: ⟦0⟧', '装备：防御：⟦0⟧'],
  ['Equipment: Breakthrough: ⟦0⟧', '装备：突破：⟦0⟧'],
  ['Equipment: Soft attack: ⟦0⟧', '装备：软攻：⟦0⟧'],
  ['Equipment: Hard attack: ⟦0⟧', '装备：硬攻：⟦0⟧'],
  ['Equipment: Piercing: ⟦0⟧', '装备：穿甲：⟦0⟧'],
  ['Mutually exclusive with: ⟦0⟧', '互斥：⟦0⟧'],
  ['Requires all of the following: ⟦0⟧', '需要以下全部：⟦0⟧'],
  ['Requires one of the following: ⟦0⟧', '需要以下之一：⟦0⟧'],
  ['Only for: ⟦0⟧', '仅适用于：⟦0⟧'],
  ['Available only with ⟦0⟧ enabled.', '仅在启用 ⟦0⟧ 时可用。'],
];
